version: '3.4'

volumes:
  datafiles:
    
networks:
  geek-shopping-network:
    driver: bridge

services:
  db:
    image: mysql:8.0.25
    container_name: geek-shopping-coupon-api-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: adm123
      MYSQL_USER: docker
      MYSQL_PASSWORD: adm123
      MYSQL_DATABASE: geek_shopping_coupon_api
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/var/lib/mysql
#      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - geek-shopping-network
  geek-shopping-coupon-api-dotnet:
    image: geek-shopping-coupon-api-dotnet
    container_name: geek-shopping-coupon-api-dotnet
    build:
      context: .
      dockerfile: GeekShopping.CouponAPI/Dockerfile
    ports:
      - "5020:80"
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    networks:
      - geek-shopping-network