name: Publish Docker Hub images

on: 
  push:
    branches: ['master']

jobs:
  CI:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build
        
      - name: Push to Docker Hub Container Registry
        run: |
          docker tag geek-shopping-coupon-api-dotnet:latest ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-dotnet:latest
          docker tag geek-shopping-coupon-api-dotnet:latest ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-dotnet:${{ github.run_id }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-dotnet:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-dotnet:${{ github.run_id }}
          
          docker tag geek-shopping-coupon-api-mysql:latest ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-mysql:latest
          docker tag geek-shopping-coupon-api-mysql:latest ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-mysql:${{ github.run_id }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-mysql:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-mysql:${{ github.run_id }}
          
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with: 
#          context: GeekShopping.CouponAPI/
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-dotnet:${{ github.run_number }}, ${{ secrets.DOCKER_USERNAME }}/geek-shopping-coupon-api-dotnet:latest