name: Publish Docker images

on: 
  push:
    branches: ['master']

jobs:
  CI:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Docker Login
        uses: docker/login-action@3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with: 
          context: GeekShopping.CouponAPI/
          push: true
          tags: leoguths/geek-shopping-coupon-api-dotnet:${{ github.run_number }}, leoguths/geek-shopping-coupon-api-dotnet:latest 
          
          #      - name: Publish to Github Packages
#        uses: docker/build-push-action@v1
#        with: 
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          tags: latest, ${{ github.run_number }}